"""Shared domain models and core contracts."""

from foliotone.core.archive_collection_models import (
    ARCHIVE_COLLECTION_PLAN_PROFILE,
    ARCHIVE_COLLECTION_PROFILE,
    MAX_ARCHIVE_COLLECTION_ATTEMPTS,
    MAX_ARCHIVE_COLLECTION_WORKERS,
    ArchiveCollectionDisposition,
    ArchiveCollectionItem,
    ArchiveCollectionItemSource,
    ArchiveCollectionItemStatus,
    ArchiveCollectionPlanFindingCounts,
    ArchiveCollectionRun,
    ArchiveCollectionRunStatus,
)
from foliotone.core.authority_models import Agent, AgentName, Contribution, ExternalIdentifier
from foliotone.core.candidate_hash_models import EbookCandidateHashRun
from foliotone.core.collection_models import (
    EBOOK_COLLECTION_FORMATS,
    MAX_EBOOK_COLLECTION_WORKERS,
    EbookCollectionItem,
    EbookCollectionRun,
)
from foliotone.core.common import Provenance, ValueAssertion
from foliotone.core.ebook_models import Edition, Series, SeriesMembership, Work
from foliotone.core.enums import (
    AgentNameType,
    AgentType,
    EbookCandidateHashPhase,
    EbookCandidateHashRunStatus,
    EbookCollectionItemStatus,
    EbookCollectionRunStatus,
    EntityKind,
    FileChangeState,
    MatchStatus,
    MediaType,
    MusicWorkRelationType,
    PresenceState,
    RelationType,
    ScanRunStatus,
    ToolCapability,
    ToolExecutionStatus,
    ValueState,
)
from foliotone.core.evidence_models import ClassificationAssertion, Evidence, Fingerprint, Relation
from foliotone.core.ids import EntityId
from foliotone.core.index_models import FileObservation, FileRecord, ScanRoot, ScanRun
from foliotone.core.music_models import (
    CatalogDesignation,
    MusicWork,
    MusicWorkRelation,
    Recording,
    Release,
    ReleaseGroup,
    ReleaseRecording,
)
from foliotone.core.relocation_models import FileRelocationCandidate, RelocationCandidateKind
from foliotone.core.resolution_models import (
    BOOK_RESOLUTION_ENTITY_KINDS,
    RESOLUTION_SUBJECT_KINDS,
    ResolutionCandidate,
    ResolutionDisposition,
    ResolutionEvidenceKind,
    ResolutionEvidenceLink,
    ResolutionEvidenceRole,
)
from foliotone.core.review_models import (
    ReviewActorKind,
    ReviewCandidateKind,
    ReviewDecision,
    ReviewDecisionValue,
    ReviewItem,
    ReviewItemState,
    ReviewType,
)
from foliotone.core.scan_events import FileScanEvent

__all__ = [
    "Agent",
    "AgentName",
    "AgentNameType",
    "AgentType",
    "ARCHIVE_COLLECTION_PLAN_PROFILE",
    "ARCHIVE_COLLECTION_PROFILE",
    "ArchiveCollectionDisposition",
    "ArchiveCollectionItem",
    "ArchiveCollectionItemSource",
    "ArchiveCollectionItemStatus",
    "ArchiveCollectionPlanFindingCounts",
    "ArchiveCollectionRun",
    "ArchiveCollectionRunStatus",
    "BOOK_RESOLUTION_ENTITY_KINDS",
    "CatalogDesignation",
    "ClassificationAssertion",
    "Contribution",
    "Edition",
    "EBOOK_COLLECTION_FORMATS",
    "MAX_EBOOK_COLLECTION_WORKERS",
    "MAX_ARCHIVE_COLLECTION_ATTEMPTS",
    "MAX_ARCHIVE_COLLECTION_WORKERS",
    "EbookCollectionItem",
    "EbookCollectionItemStatus",
    "EbookCollectionRun",
    "EbookCollectionRunStatus",
    "EbookCandidateHashPhase",
    "EbookCandidateHashRun",
    "EbookCandidateHashRunStatus",
    "EntityId",
    "EntityKind",
    "Evidence",
    "ExternalIdentifier",
    "FileChangeState",
    "FileObservation",
    "FileRecord",
    "FileRelocationCandidate",
    "FileScanEvent",
    "Fingerprint",
    "MatchStatus",
    "MediaType",
    "MusicWork",
    "MusicWorkRelation",
    "MusicWorkRelationType",
    "PresenceState",
    "Provenance",
    "Recording",
    "Relation",
    "RelationType",
    "Release",
    "ReleaseGroup",
    "ReleaseRecording",
    "RelocationCandidateKind",
    "RESOLUTION_SUBJECT_KINDS",
    "ResolutionCandidate",
    "ResolutionDisposition",
    "ResolutionEvidenceKind",
    "ResolutionEvidenceLink",
    "ResolutionEvidenceRole",
    "ReviewActorKind",
    "ReviewCandidateKind",
    "ReviewDecision",
    "ReviewDecisionValue",
    "ReviewItem",
    "ReviewItemState",
    "ReviewType",
    "ScanRoot",
    "ScanRun",
    "ScanRunStatus",
    "Series",
    "SeriesMembership",
    "ToolCapability",
    "ToolExecutionStatus",
    "ValueAssertion",
    "ValueState",
    "Work",
]
