"""Core domain enumerations."""

from enum import StrEnum


class EntityKind(StrEnum):
    FILE = "FILE"
    FILE_OBSERVATION = "FILE_OBSERVATION"
    AGENT = "AGENT"
    WORK = "WORK"
    EDITION = "EDITION"
    SERIES = "SERIES"
    MUSIC_WORK = "MUSIC_WORK"
    RECORDING = "RECORDING"
    RELEASE_GROUP = "RELEASE_GROUP"
    RELEASE = "RELEASE"


class MediaType(StrEnum):
    EBOOK = "EBOOK"
    MUSIC = "MUSIC"
    UNKNOWN = "UNKNOWN"


class PresenceState(StrEnum):
    PRESENT = "PRESENT"
    MISSING = "MISSING"
    DELETED = "DELETED"


class FileChangeState(StrEnum):
    NEW = "NEW"
    UNCHANGED = "UNCHANGED"
    MODIFIED = "MODIFIED"
    REAPPEARED = "REAPPEARED"
    MISSING = "MISSING"
    MOVED = "MOVED"
    RENAMED = "RENAMED"
    DELETED = "DELETED"


class ScanRunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"


class ValueState(StrEnum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    EXTERNAL = "EXTERNAL"
    CANONICAL = "CANONICAL"
    USER_CONFIRMED = "USER_CONFIRMED"


class AgentType(StrEnum):
    PERSON = "PERSON"
    GROUP = "GROUP"
    ORGANIZATION = "ORGANIZATION"
    ENSEMBLE = "ENSEMBLE"
    ORCHESTRA = "ORCHESTRA"
    CHOIR = "CHOIR"
    UNKNOWN = "UNKNOWN"


class AgentNameType(StrEnum):
    CANONICAL = "CANONICAL"
    SORT_NAME = "SORT_NAME"
    ALIAS = "ALIAS"
    PSEUDONYM = "PSEUDONYM"
    CREDITED_AS = "CREDITED_AS"
    TRANSLITERATION = "TRANSLITERATION"
    FORMER_NAME = "FORMER_NAME"


class MusicWorkRelationType(StrEnum):
    PART_OF = "PART_OF"
    ARRANGEMENT_OF = "ARRANGEMENT_OF"
    TRANSLATION_OF = "TRANSLATION_OF"
    DERIVED_FROM = "DERIVED_FROM"
    REVISION_OF = "REVISION_OF"


class MatchStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROBABLE = "PROBABLE"
    POSSIBLE = "POSSIBLE"
    REJECTED = "REJECTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class RelationType(StrEnum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    CONTENT_DUPLICATE = "CONTENT_DUPLICATE"
    FORMAT_VARIANT = "FORMAT_VARIANT"
    QUALITY_VARIANT = "QUALITY_VARIANT"
    TRANSCODE = "TRANSCODE"
    SAME_WORK = "SAME_WORK"
    SAME_EDITION = "SAME_EDITION"
    DIFFERENT_EDITION = "DIFFERENT_EDITION"
    SAME_MUSIC_WORK = "SAME_MUSIC_WORK"
    SAME_RECORDING = "SAME_RECORDING"
    SAME_RELEASE_GROUP = "SAME_RELEASE_GROUP"
    SAME_RELEASE = "SAME_RELEASE"
    DIFFERENT_RECORDING = "DIFFERENT_RECORDING"
    DIFFERENT_RELEASE = "DIFFERENT_RELEASE"


class ToolCapability(StrEnum):
    READ_METADATA = "READ_METADATA"
    EXTRACT_TEXT = "EXTRACT_TEXT"
    TECHNICAL_METADATA = "TECHNICAL_METADATA"
    FINGERPRINT = "FINGERPRINT"
    DUPLICATE_ANALYSIS = "DUPLICATE_ANALYSIS"
    COMPLETENESS_ANALYSIS = "COMPLETENESS_ANALYSIS"
    LIBRARY_READ = "LIBRARY_READ"
    STATUS_REPORT = "STATUS_REPORT"


class ToolExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
