"""Persistence implementations behind provider-independent core contracts."""

from foliotone.persistence.calibre_library import (
    CalibreLibraryStoreError,
    SQLiteCalibreLibraryStore,
)
from foliotone.persistence.contracts import Repository
from foliotone.persistence.ebook_candidate_hash import (
    EbookCandidateHashLeaseError,
    SQLiteEbookCandidateHashRunStore,
)
from foliotone.persistence.ebook_collection import (
    EBOOK_COLLECTION_PLAN_BATCH_SIZE,
    CreatedEbookCollectionRun,
    EbookCollectionCounts,
    EbookCollectionExecutionSummary,
    EbookCollectionFindingSummary,
    EbookCollectionStoreError,
    EbookCollectionWorkItem,
    SQLiteEbookCollectionStore,
)
from foliotone.persistence.ebook_collection_report import (
    EBOOK_COLLECTION_REPORT_FETCH_SIZE,
    EbookCollectionCandidateGroup,
    EbookCollectionCandidateMember,
    EbookCollectionCandidateSet,
    EbookCollectionFindingAggregate,
    EbookCollectionReportSnapshot,
    EbookCollectionReportStoreError,
    EbookCollectionReviewFinding,
    EbookCollectionReviewItem,
    SQLiteEbookCollectionReportStore,
)
from foliotone.persistence.ebook_inventory_report import (
    EbookInventoryDuplicateGroup,
    EbookInventoryDuplicateMember,
    EbookInventoryDuplicateSet,
    EbookInventoryFormatAggregate,
    EbookInventoryReportSnapshot,
    EbookInventoryReportStoreError,
    SQLiteEbookInventoryReportStore,
)
from foliotone.persistence.evidence_queries import (
    MAX_EVIDENCE_QUERY_EXECUTIONS,
    MAX_EVIDENCE_QUERY_FINGERPRINTS,
    MAX_EVIDENCE_QUERY_OBSERVATIONS,
    MAX_EVIDENCE_QUERY_RESULTS,
    EvidenceQueryLimitError,
    ObservationEvidenceRecords,
    load_observation_evidence,
)
from foliotone.persistence.relation_candidates import (
    RelationCandidateStoreError,
    SQLiteRelationCandidateStore,
)
from foliotone.persistence.resolution_review import (
    MAX_RESOLUTION_EVIDENCE,
    MAX_RESOLUTION_PAGE,
    MAX_REVIEW_PAGE,
    ResolutionCandidatePage,
    ResolutionReviewStoreError,
    ReviewItemPage,
    SQLiteResolutionReviewStore,
)
from foliotone.persistence.scan_root_lease import (
    OwnedScanRootWriteLease,
    ScanRootWriteLeaseError,
    ScanRootWriteOwnerKind,
    SQLiteScanRootWriteLeaseStore,
    scan_root_write_scope,
)
from foliotone.persistence.sqlite import (
    SQLiteRepository,
    alembic_config,
    create_sqlite_engine,
    create_sqlite_read_only_engine,
    migrate,
    repository,
    transaction,
)

__all__ = [
    "Repository",
    "CalibreLibraryStoreError",
    "MAX_RESOLUTION_EVIDENCE",
    "MAX_RESOLUTION_PAGE",
    "MAX_REVIEW_PAGE",
    "MAX_EVIDENCE_QUERY_EXECUTIONS",
    "MAX_EVIDENCE_QUERY_FINGERPRINTS",
    "MAX_EVIDENCE_QUERY_OBSERVATIONS",
    "MAX_EVIDENCE_QUERY_RESULTS",
    "EvidenceQueryLimitError",
    "EBOOK_COLLECTION_PLAN_BATCH_SIZE",
    "CreatedEbookCollectionRun",
    "EbookCollectionCounts",
    "EbookCollectionExecutionSummary",
    "EbookCollectionFindingSummary",
    "EbookCollectionStoreError",
    "EbookCollectionWorkItem",
    "EbookCandidateHashLeaseError",
    "EbookInventoryDuplicateGroup",
    "EbookInventoryDuplicateMember",
    "EbookInventoryDuplicateSet",
    "EbookInventoryFormatAggregate",
    "EbookInventoryReportSnapshot",
    "EbookInventoryReportStoreError",
    "EBOOK_COLLECTION_REPORT_FETCH_SIZE",
    "EbookCollectionCandidateGroup",
    "EbookCollectionCandidateMember",
    "EbookCollectionCandidateSet",
    "EbookCollectionFindingAggregate",
    "EbookCollectionReportSnapshot",
    "EbookCollectionReportStoreError",
    "EbookCollectionReviewFinding",
    "EbookCollectionReviewItem",
    "ObservationEvidenceRecords",
    "SQLiteRepository",
    "SQLiteEbookCollectionStore",
    "SQLiteCalibreLibraryStore",
    "SQLiteEbookCandidateHashRunStore",
    "SQLiteEbookInventoryReportStore",
    "SQLiteEbookCollectionReportStore",
    "OwnedScanRootWriteLease",
    "ScanRootWriteLeaseError",
    "ScanRootWriteOwnerKind",
    "ResolutionCandidatePage",
    "ResolutionReviewStoreError",
    "RelationCandidateStoreError",
    "ReviewItemPage",
    "SQLiteResolutionReviewStore",
    "SQLiteRelationCandidateStore",
    "SQLiteScanRootWriteLeaseStore",
    "scan_root_write_scope",
    "alembic_config",
    "create_sqlite_engine",
    "create_sqlite_read_only_engine",
    "migrate",
    "load_observation_evidence",
    "repository",
    "transaction",
]
