"""External knowledge enrichment and provider boundaries."""

from foliotone.enrichment.contracts import (
    BOOK_KNOWLEDGE_QUERY_FINGERPRINT_DOMAIN,
    BookKnowledgeDTO,
    BookKnowledgeQuery,
    BookKnowledgeResponse,
    KnowledgeProviderDescriptor,
    KnowledgeProviderMode,
    ProviderAccessMode,
    ProviderCachePolicy,
    StructuredKnowledgeBookResult,
    provider_policy_from_legacy,
)
from foliotone.enrichment.provider_cache_contracts import (
    PROVIDER_MAPPING_INPUT_KEY_DOMAIN,
    PROVIDER_SOURCE_CACHE_KEY_DOMAIN,
    ProviderCacheContentSlot,
    ProviderCacheFailureSlot,
    ProviderCacheFreshness,
    ProviderCacheLimits,
    ProviderCachePayloadKind,
    ProviderCacheResultStatus,
    ProviderCacheSlots,
    provider_mapping_input_key,
    provider_mapping_input_key_bytes,
    provider_source_cache_key,
    provider_source_cache_key_bytes,
)
from foliotone.enrichment.providers import SyntheticBookKnowledgeProvider

__all__ = [
    "BookKnowledgeDTO",
    "BOOK_KNOWLEDGE_QUERY_FINGERPRINT_DOMAIN",
    "BookKnowledgeQuery",
    "BookKnowledgeResponse",
    "KnowledgeProviderDescriptor",
    "KnowledgeProviderMode",
    "ProviderAccessMode",
    "ProviderCachePolicy",
    "ProviderCacheContentSlot",
    "ProviderCacheFailureSlot",
    "ProviderCacheFreshness",
    "ProviderCacheLimits",
    "PROVIDER_MAPPING_INPUT_KEY_DOMAIN",
    "PROVIDER_SOURCE_CACHE_KEY_DOMAIN",
    "ProviderCachePayloadKind",
    "ProviderCacheResultStatus",
    "ProviderCacheSlots",
    "provider_mapping_input_key",
    "provider_mapping_input_key_bytes",
    "provider_source_cache_key",
    "provider_source_cache_key_bytes",
    "StructuredKnowledgeBookResult",
    "SyntheticBookKnowledgeProvider",
    "provider_policy_from_legacy",
]
