"""Public contracts for immutable, non-executable e-book operation recipes."""

from foliotone.ebook_operation_recipes import contracts as _contracts
from foliotone.ebook_operation_recipes.contracts import *  # noqa: F403
from foliotone.ebook_operation_recipes.planner import (
    EbookOperationRecipeCandidateInputs,
    EbookOperationRecipePlanInputs,
    build_ebook_operation_expected_output,
    build_ebook_operation_processor_requirement,
    build_ebook_operation_recipe_candidate,
    build_ebook_operation_recipe_plan,
    build_ebook_operation_source_snapshot,
    build_non_executable_ebook_operation_recipe_plan,
)
from foliotone.ebook_operation_recipes.serialization import (
    canonical_ebook_operation_recipe_candidate_payload,
    canonical_ebook_operation_recipe_plan_payload,
    ebook_operation_expected_output_fingerprint,
    ebook_operation_precondition_fingerprint,
    ebook_operation_processor_requirement_fingerprint,
    ebook_operation_recipe_candidate_content_hash,
    ebook_operation_recipe_candidate_evidence_fingerprint,
    ebook_operation_recipe_candidate_id,
    ebook_operation_recipe_plan_content_hash,
    ebook_operation_recipe_plan_id,
    ebook_operation_recovery_requirement_fingerprint,
    ebook_operation_source_evidence_fingerprint,
    ebook_operation_verification_fingerprint,
    ebook_operation_workspace_requirement_fingerprint,
    serialize_ebook_operation_recipe_candidate,
    serialize_ebook_operation_recipe_plan,
)

__all__ = [
    *_contracts.__all__,
    "EbookOperationRecipeCandidateInputs",
    "EbookOperationRecipePlanInputs",
    "build_ebook_operation_expected_output",
    "build_ebook_operation_processor_requirement",
    "build_ebook_operation_recipe_candidate",
    "build_ebook_operation_recipe_plan",
    "build_ebook_operation_source_snapshot",
    "build_non_executable_ebook_operation_recipe_plan",
    "canonical_ebook_operation_recipe_candidate_payload",
    "canonical_ebook_operation_recipe_plan_payload",
    "ebook_operation_expected_output_fingerprint",
    "ebook_operation_precondition_fingerprint",
    "ebook_operation_processor_requirement_fingerprint",
    "ebook_operation_recipe_candidate_content_hash",
    "ebook_operation_recipe_candidate_evidence_fingerprint",
    "ebook_operation_recipe_candidate_id",
    "ebook_operation_recipe_plan_content_hash",
    "ebook_operation_recipe_plan_id",
    "ebook_operation_recovery_requirement_fingerprint",
    "ebook_operation_source_evidence_fingerprint",
    "ebook_operation_verification_fingerprint",
    "ebook_operation_workspace_requirement_fingerprint",
    "serialize_ebook_operation_recipe_candidate",
    "serialize_ebook_operation_recipe_plan",
]
